# Generated by Django 5.1.4 on 2024-12-17 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('discount_type', models.CharField(choices=[('FIXED', '정액 할인'), ('RATE', '정률 할인')], default='RATE', max_length=5)),
                ('discount_value', models.IntegerField()),
                ('dsl', models.TextField(blank=True, help_text='Generated DSL for campaign conditions', null=True)),
                ('brand_ids', models.JSONField(default=list)),
                ('product_ids', models.JSONField(default=list)),
                ('category_ids', models.JSONField(default=list)),
                ('minimum_customer_segment', models.IntegerField(null=True)),
                ('minimum_mov', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CostShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=100)),
                ('share_type', models.CharField(choices=[('FIXED', '정액 분담'), ('RATE', '정률 분담'), ('RATIO', '비율 분담')], max_length=5)),
                ('share_value', models.IntegerField()),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_shares', to='app.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.IntegerField()),
                ('category', models.CharField(choices=[('스킨케어', '스킨케어'), ('마스크팩', '마스크팩'), ('클렌징', '클렌징'), ('선케어', '선케어'), ('메이크업', '메이크업'), ('네일', '네일'), ('뷰티소품', '뷰티소품'), ('더모 코스메틱', '더모 코스메틱'), ('맨즈케어', '맨즈케어'), ('향수/디퓨저', '향수/디퓨저'), ('헤어케어', '헤어케어'), ('바디케어', '바디케어'), ('건강식품', '건강식품'), ('푸드', '푸드'), ('구강용품', '구강용품'), ('헬스/건강용품', '헬스/건강용품'), ('여성/위생용품', '여성/위생용품'), ('패션', '패션'), ('리빙/가전', '리빙/가전'), ('취미/펫용품', '취미/펫용품')], max_length=50)),
                ('thumbnail', models.CharField(blank=True, max_length=200, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='products', to='app.brand')),
            ],
        ),
    ]
